### ISSUE TITLE
HEAD requests contain a body in error cases

### ISSUE THREAD

**Issue by dsboulder** [fujita/swift3#74]
In the GETorHEAD() method I found that most HEAD requests do not have a body when we execute this code:
```
  if env['REQUEST_METHOD'] == 'HEAD':
    app_iter = None

  # then later:
  if is_success(status):
    return Response(status=status, headers=new_hdrs, app_iter=app_iter)
```

But when there are errors (such as a key-not-found 404), we return the result of a call to `get_err_response`.  This method *always* returns a body:
```
    resp = Response(content_type='text/xml')
    resp.status = error_table[code][0]
    resp.body = """%s
        <Error><Code>%s</Code><Message>%s</Message></Error>
    """ % (XML_HEADER, code, error_table[code][1])
    return resp
```

HEAD requests **must not return a body** or we're breaking the HTTP spec.  This manifested for me when I did a HEAD followed by a PUT request over the same HTTP connection.  The 2nd request fails horribly because there's an unexpected body still on the wire.  I think it's easy to fix, just make sure that the `get_err_response` method does not add a body if the original request is a HEAD.

**Comment by fujita** [comment]
Please try https://github.com/stackforge/swift3
